# Generated by Django 5.0 on 2025-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_type_36f2e6_idx",
        ),
        migrations.RenameField(
            model_name="notificationpreference",
            old_name="order_status_notifications",
            new_name="system_notifications",
        ),
        migrations.RenameField(
            model_name="notificationpreference",
            old_name="push_notifications",
            new_name="websocket_notifications",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="sound_notifications",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_order", "New Order"),
                    ("order_status", "Order Status Update"),
                    ("payment", "Payment"),
                    ("system", "System"),
                    ("custom", "Custom"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
